FROM domain-base

RUN git clone https://github.com/onsplatform/domain_schema.git /src

WORKDIR src
RUN pip install pipenv
RUN pipenv install --dev --system --deploy

EXPOSE 80

CMD python manage.py runserver 0.0.0.0:80
